### ISSUE TITLE
What decencies are with the jar?

### ISSUE THREAD

**Issue by mhenke** [raymyers/JHaml#4]
Example for a less engine jar, I had to add js.jar for rhino.

I am receiving the same type of error message so assume I am missing a dependant jar. I tried adding groovy-all-1.6.0.jar but still am getting the error.

Thanks,

**Comment by mhenke** [comment]
I am able to create 
engine = loader.create("com.cadrlife.jhaml.internal.util.IndentUtils").init();

add the guava-r06.jar

but 

engine = loader.create("com.cadrlife.jhaml.Jhaml").init();

still fails

**Comment by mhenke** [comment]
figured it out
    loadPaths[2] = expandPath("commons-lang-2.5.jar");
    loadPaths[3] = expandPath("markdownj-0.3.0-1.0.2b4.jar");
    loadPaths[4] = expandPath("guava-r06.jar");

**Comment by raymyers** [comment]
Looks like you figured this out already, but the jar dependencies are listed in **build.gradle**.

```
compile group: 'commons-lang', name: 'commons-lang', version: '2.5'
compile group: 'com.google.guava', name: 'guava', version: 'r06'
compile group: 'org.markdownj', name: 'markdownj', version: '0.3.0-1.0.2b4'
```

When **build.gradle** runs, it fetches these from maven repositories. For convenience, they are also provided in the **lib** folder
