### ISSUE TITLE
Publish in Maven repo

### ISSUE THREAD

**Issue by jacek99** [raymyers/JHaml#5]
Pls add JHaml to a Maven repo, your own or a public one like clojars is fine. Would like to use it with Maven based projects.

**Comment by raymyers** [comment]
Didn't realize this would be so easy to do :)

Repo: https://raw.github.com/raymyers/raymyers-mvn-repo/master/releases
Group: com.cadrlife.jhaml
Name: jhaml
version: 0.1.4

Thanks for the idea!

**Comment by splix** [comment]
@raymyers seems that you've moved Maven repo? Could you please tell a url for new repo? Thanks

**Comment by raymyers** [comment]
Hmm, should still be there. It's hosted in this project: https://github.com/raymyers/raymyers-mvn-repo.

If that isn't resolving, maybe hosting maven repos from github doesn't work anymore.

I've got a Maven central account now though, so I can try and get it in there.

**Comment by splix** [comment]
Oh, i'm sorry. I was using invalid url :( GitHub answered with default 404, so i've decided that it's moved out. Sorry
